20170615-05:34:20: Session FIX.4.4:02f8e7cb-6a9a-4dff-8ab8-e246b8d1800c->BTCC-FIX-SERVER schedule is daily, 00:00:00-UTC - 00:00:00-UTC
20170615-05:34:20: Created session: FIX.4.4:02f8e7cb-6a9a-4dff-8ab8-e246b8d1800c->BTCC-FIX-SERVER
20170615-05:34:22: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:34:22: Initiated logon request
20170615-05:34:22: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:34:22: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

20170615-05:34:33: Disconnecting: Timed out waiting for logon response
20170615-05:34:34: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:34:34: Initiated logon request
20170615-05:34:34: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:34:34: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

20170615-05:34:45: Disconnecting: Timed out waiting for logon response
20170615-05:34:46: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:34:46: Initiated logon request
20170615-05:34:47: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:34:47: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

20170615-05:34:58: Disconnecting: Timed out waiting for logon response
20170615-05:34:59: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:34:59: Initiated logon request
20170615-05:34:59: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:34:59: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

20170615-05:35:10: Disconnecting: Timed out waiting for logon response
20170615-05:35:11: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:35:11: Initiated logon request
20170615-05:35:11: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:35:11: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

20170615-05:35:22: Disconnecting: Timed out waiting for logon response
20170615-05:35:23: Application exception in toAdmin()
TypeError: toAdmin() takes exactly 2 arguments (3 given)

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:229)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.toAdmin(Unknown Source)
	at quickfix.Session.sendRaw(Session.java:2391)
	at quickfix.Session.generateLogon(Session.java:1867)
	at quickfix.Session.next(Session.java:1767)
	at quickfix.mina.SessionConnector$SessionTimerTask.run(SessionConnector.java:283)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.FutureTask.runAndReset(FutureTask.java:198)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:138)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:238)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:987)
	at org.quickfixj.java4.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:528)
	at java.lang.Thread.run(Thread.java:745)

20170615-05:35:23: Initiated logon request
20170615-05:35:26: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20170615-05:35:26: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

quickfix.RuntimeError: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at quickfix.Session.next(Session.java:1095)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:114)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:77)
	at quickfix.SocketInitiator.block(SocketInitiator.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.mainRun$3(BTCCFIXClient.py:57)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(BTCCFIXClient.py:61)
	at org.python.pycode._pyx0.call_function(BTCCFIXClient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Caused by: Traceback (most recent call last):
  File "/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py", line 50, in fromAdmin
    self.log.info(sessionID + "------ fromAdmin--------" + msg.toString())
TypeError: unsupported operand type(s) for +: 'quickfix.SessionID' and 'str'

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject._basic_add(PyObject.java:2141)
	at org.python.core.PyObject._add(PyObject.java:2119)
	at BTCCFIXClientApp$py.fromAdmin$3(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py:50)
	at BTCCFIXClientApp$py.call_function(/Users/junpengzhang/doc/github/jython_fix/jythonFix/BTCCFIXClientApp.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.proxies.BTCCFIXClientApp$BTCCFIXClientApp$0.fromAdmin(Unknown Source)
	at quickfix.Session.fromCallback(Session.java:1696)
	at quickfix.Session.verify(Session.java:1650)
	at quickfix.Session.nextLogon(Session.java:1979)
	at quickfix.Session.next(Session.java:973)
	... 26 more

